//! Executable Rust serialization snapshots, checked against TypeScript's public shapes.
use super::FrontendSettings;
use crate::{
    ai::{self, AiProvider},
    config::{AppSettings, HostPlatform, dictation_default_for, writing_tools_default_for},
};

#[test]
fn native_contracts() {
    let providers = ai::provider_infos();
    let models: serde_json::Map<String, serde_json::Value> = AiProvider::all()
        .iter()
        .map(|provider| {
            (
                provider.as_str().to_owned(),
                serde_json::to_value(ai::curated_models_for(*provider)).unwrap(),
            )
        })
        .collect();
    let settings: serde_json::Map<String, serde_json::Value> = [
        ("windows", HostPlatform::Windows),
        ("linux", HostPlatform::Linux),
    ]
    .into_iter()
    .map(|(name, host)| {
        let mut settings = AppSettings::default();
        settings.dictation.shortcut = dictation_default_for(host);
        settings.writing_tools.shortcut = writing_tools_default_for(host);
        let frontend = FrontendSettings::from(settings);
        let json = serde_json::to_value(&frontend).unwrap();
        // Verify the actual serde roundtrip, including defaults and renames.
        let decoded: FrontendSettings = serde_json::from_value(json.clone()).unwrap();
        assert_eq!(serde_json::to_value(decoded).unwrap(), json);
        (name.to_owned(), json)
    })
    .collect();
    let mut source = String::from(
        "// Generated by `bun run generate:contracts`. Do not edit.\nimport type { AiModelInfo, AiProviderInfo, AppSettings } from '../types';\ntype ReadonlyShape<T> = T extends object ? { readonly [K in keyof T]: ReadonlyShape<T[K]> } : T;\n",
    );
    for (name, value, shape) in [
        (
            "NATIVE_PROVIDERS",
            serde_json::to_value(providers).unwrap(),
            "ReadonlyShape<AiProviderInfo[]>",
        ),
        (
            "NATIVE_MODELS",
            serde_json::Value::Object(models),
            "ReadonlyShape<Record<'gemini' | 'zen' | 'go' | 'custom', AiModelInfo[]>>",
        ),
        (
            "NATIVE_SETTINGS",
            serde_json::Value::Object(settings),
            "ReadonlyShape<Record<'windows' | 'linux', AppSettings>>",
        ),
    ] {
        source.push_str(&format!(
            "export const {name} = {} as const satisfies {shape};\n",
            serde_json::to_string_pretty(&value).unwrap()
        ));
    }
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../src/platform/contracts.generated.ts");
    if std::env::var("KIVO_GENERATE_CONTRACTS").as_deref() == Ok("1") {
        std::fs::write(path, source).unwrap();
    } else {
        assert_eq!(
            std::fs::read_to_string(path).unwrap().replace("\r\n", "\n"),
            source,
            "Native serialization/catalog contracts changed. Run bun run generate:contracts."
        );
    }
}
