import { afterEach, expect, it } from "bun:test";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const cli = join(root, "node_modules/@astryxdesign/cli/clients/cli/bin/astryx.mjs");
const directories: string[] = [];

afterEach(() => {
  for (const directory of directories.splice(0))
    rmSync(directory, { recursive: true, force: true });
});

it("theme variant declarations are independent of component directory order", async () => {
  const directory = mkdtempSync(join(tmpdir(), "kivo-theme-"));
  directories.push(directory);
  const declarations: string[] = [];
  for (const direction of [1, -1]) {
    const preload = join(directory, `order-${direction}.mjs`);
    await Bun.write(
      preload,
      `import fs from "node:fs";
import { mock } from "bun:test";
const read = fs.readdirSync;
const readdirSync = (...args) => {
  const entries = read(...args);
  if (String(args[0]).replaceAll("\\\\", "/").includes("@astryxdesign/core/src")) {
    entries.sort((a, b) => ${direction} * String(a.name ?? a).localeCompare(String(b.name ?? b)));
  }
  return entries;
};
mock.module("node:fs", () => ({ ...fs, readdirSync, default: { ...fs, readdirSync } }));
`,
    );
    const output = join(directory, `order-${direction}`, "kivo.css");
    const result = Bun.spawnSync(
      [
        process.execPath,
        "--preload",
        preload,
        cli,
        "theme",
        "build",
        "src/theme/kivo.ts",
        "-o",
        output,
      ],
      { cwd: root },
    );
    expect(result.stderr.toString()).not.toContain("Error");
    expect(result.exitCode).toBe(0);
    const content = await Bun.file(output.replace(/\.css$/, ".variants.d.ts")).text();
    declarations.push(content.slice(content.indexOf("// Generated by astryx theme build")));
  }
  expect(declarations[0]).toBe(declarations[1]);
  expect(declarations[0]).toContain("BadgeVariantMap");
  // These are built-in Avatar variants, so they must not be augmented as custom values.
  expect(declarations[0]).not.toContain("AvatarStatusDotVariantMap");
}, 15_000);
