import * as stylex from "@stylexjs/stylex";
export const styles = stylex.create({
  shell: {
    display: "grid",
    gridTemplateColumns: "184px minmax(0, 1fr)",
    width: "100%",
    height: "100%",
    backgroundColor: "var(--color-background-body)",
    "@media (width <= 680px)": {
      gridTemplateColumns: "148px minmax(0, 1fr)",
    },
  },
  sidebar: {
    display: "flex",
    flexDirection: "column",
    minWidth: "0",
    paddingBlockStart: "22px",
    paddingBlockEnd: "16px",
    paddingInline: "10px",
    color: "var(--color-text-primary)",
    backgroundColor: "var(--color-background-surface)",
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: "var(--color-border)",
    "@media (width <= 680px)": {
      paddingInline: "8px",
    },
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: "9px",
    paddingInline: "9px",
    paddingBlockEnd: "23px",
    fontSize: "16px",
    letterSpacing: "-0.025em",
  },
  brandMark: {
    display: "grid",
    placeItems: "center",
    width: "27px",
    height: "27px",
    color: "var(--color-on-accent)",
    backgroundColor: "var(--color-accent)",
    borderRadius: "7px",
  },
  brandName: {
    fontWeight: 680,
  },
  nav: {
    display: "grid",
    gap: "2px",
  },
  groupLabel: {
    display: "none",
    marginBlockStart: "18px",
    marginInline: "10px",
    marginBlockEnd: "5px",
    color: "var(--kivo-text-quaternary)",
    fontSize: "9px",
    fontWeight: 700,
    letterSpacing: "0.13em",
    textTransform: "uppercase",
  },
  navButton: {
    display: "flex",
    alignItems: "center",
    gap: "9px",
    height: "34px",
    paddingInline: "9px",
    textAlign: "left",
    color: "var(--color-text-secondary)",
    backgroundColor: "transparent",
    borderWidth: "0",
    borderRadius: "var(--radius-inner)",
    fontSize: "12.5px",
    cursor: "pointer",
    transitionProperty: "background-color, color",
    transitionDuration: "120ms",
    ":hover": {
      color: "var(--color-text-primary)",
      backgroundColor: "var(--kivo-hover)",
    },
  },
  navButtonCurrent: {
    color: "var(--color-text-primary)",
    backgroundColor: "var(--kivo-selected)",
    fontWeight: 650,
  },
  sidebarStatus: {
    display: "flex",
    alignItems: "center",
    gap: "9px",
    marginBlockStart: "auto",
    marginInline: "8px",
    marginBlockEnd: "0",
    paddingBlockStart: "12px",
    color: "var(--kivo-text-tertiary)",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "var(--color-border)",
    fontSize: "10.5px",
  },
  statusDot: {
    width: "7px",
    height: "7px",
    backgroundColor: "var(--kivo-signal)",
    borderRadius: "50%",
  },
  statusDotPaused: {
    backgroundColor: "var(--kivo-text-tertiary)",
  },
  version: {
    marginInlineStart: "auto",
    color: "var(--kivo-text-tertiary)",
    fontSize: "10px",
    fontVariantNumeric: "tabular-nums",
  },
  main: {
    minWidth: "0",
    paddingBlockStart: "42px",
    paddingInline: "48px",
    paddingBlockEnd: "36px",
    overflow: "auto",
    outline: "none",
    backgroundColor: "var(--color-background-body)",
    scrollbarGutter: "stable",
    "@media (width <= 680px)": {
      paddingBlock: "28px",
      paddingInline: "22px",
    },
  },
  content: {
    maxWidth: "620px",
    marginInline: "auto",
  },
  contentHeader: {
    marginBottom: "27px",
  },
  contentTitle: {
    margin: "0 0 4px",
    fontSize: "25px",
    fontWeight: 650,
    lineHeight: 1.2,
    letterSpacing: "-0.03em",
  },
  contentSubtitle: {
    maxWidth: "560px",
    margin: "0",
    color: "var(--color-text-secondary)",
    fontSize: "13px",
  },
  group: {
    marginBlockEnd: "22px",
  },
  groupHeader: {
    margin: "0 0 9px 2px",
    color: "var(--kivo-text-tertiary)",
    fontSize: "10px",
    fontWeight: 750,
    letterSpacing: "0.11em",
    textTransform: "uppercase",
  },
  groupBody: {
    overflow: "hidden",
    backgroundColor: "var(--color-background-card)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--color-border)",
    borderRadius: "var(--radius-element)",
  },
  row: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "18px",
    minHeight: "62px",
    paddingBlock: "12px",
    paddingInline: "15px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "var(--color-border)",
    ":first-child": {
      borderTopWidth: "0",
    },
    "@media (width <= 680px)": {
      flexDirection: "column",
      alignItems: "flex-start",
      gap: "10px",
    },
  },
  rowStacked: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: "9px",
  },
  rowLabel: {
    display: "grid",
    gap: "3px",
    minWidth: "0",
  },
  rowTitle: {
    fontSize: "13.5px",
    fontWeight: 620,
    letterSpacing: "-0.01em",
  },
  rowDescription: {
    color: "var(--color-text-secondary)",
    fontSize: "11.5px",
    lineHeight: "1.35",
  },
  rowControl: {
    flexShrink: "0",
    maxWidth: "58%",
    "@media (width <= 680px)": {
      maxWidth: "100%",
    },
  },
  rowControlStacked: {
    width: "100%",
    maxWidth: "none",
  },
  groupFooter: {
    display: "flex",
    paddingBlock: "10px",
    paddingInline: "12px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: "var(--color-border)",
  },
  groupFooterSplit: {
    justifyContent: "space-between",
  },
  notice: {
    position: "sticky",
    bottom: "10px",
    zIndex: 2,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    maxWidth: "620px",
    marginBlockStart: "10px",
    marginInline: "auto",
    paddingBlock: "10px",
    paddingInline: "11px",
    paddingInlineStart: "13px",
    backgroundColor: "var(--color-background-card)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--color-border)",
    borderRadius: "var(--radius-element)",
    boxShadow: "var(--shadow-high)",
  },
  note: {
    marginBlockStart: "2px",
    marginBlockEnd: "14px",
    color: "var(--color-text-secondary)",
    fontSize: "12px",
    lineHeight: "1.4",
  },
  empty: {
    color: "var(--color-text-secondary)",
    fontSize: "12.5px",
  },
  field: {
    minHeight: "30px",
    paddingBlock: "0",
    paddingInline: "9px",
    color: "var(--color-text-primary)",
    backgroundColor: "var(--color-background-card)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "var(--color-border)",
    borderRadius: "var(--radius-inner)",
    fontSize: "13px",
  },
  growField: {
    flex: 1,
    minWidth: "0",
  },
  numberField: {
    width: "120px",
  },
  keyEditor: {
    display: "flex",
    gap: "7px",
    width: "100%",
  },
  permissionControl: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  granted: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    color: "var(--color-success)",
    fontSize: "12px",
    whiteSpace: "nowrap",
  },
  textLink: {
    padding: "0",
    color: "var(--color-text-accent)",
    backgroundColor: "transparent",
    borderWidth: "0",
    fontSize: "12px",
    cursor: "pointer",
    ":hover": {
      textDecoration: "underline",
    },
  },
  linkStart: {
    justifySelf: "start",
  },
  lockup: {
    display: "flex",
    alignItems: "center",
    gap: "13px",
    marginBlockEnd: "24px",
  },
  lockupMark: {
    display: "grid",
    placeItems: "center",
    width: "54px",
    height: "54px",
    color: "var(--color-on-accent)",
    backgroundColor: "var(--color-accent)",
    borderRadius: "13px",
  },
  lockupTitle: {
    margin: "0",
    fontSize: "18px",
  },
  lockupVersion: {
    margin: "0",
    color: "var(--color-text-secondary)",
  },
  aboutLinks: {
    display: "grid",
    gap: "8px",
    color: "var(--color-text-secondary)",
  },
  privacyNote: {
    marginTop: "28px",
    color: "var(--kivo-text-tertiary)",
    fontSize: "11px",
  },
});
