// Generated by `bun run generate:contracts`. Do not edit.
import type { AiModelInfo, AiProviderInfo, AppSettings } from '../types';
type ReadonlyShape<T> = T extends object ? { readonly [K in keyof T]: ReadonlyShape<T[K]> } : T;
export const NATIVE_PROVIDERS = [
  {
    "defaultBaseUrl": null,
    "defaultModel": "gemini-3.8-flash",
    "id": "gemini",
    "keyOptional": false,
    "keyUrl": "https://aistudio.google.com/app/apikey",
    "label": "Gemini",
    "supportsLinkSummary": true,
    "testUsesQuota": true
  },
  {
    "defaultBaseUrl": null,
    "defaultModel": "gemini-3.8-flash",
    "id": "zen",
    "keyOptional": false,
    "keyUrl": "https://opencode.ai/auth",
    "label": "OpenCode Zen",
    "supportsLinkSummary": false,
    "testUsesQuota": true
  },
  {
    "defaultBaseUrl": null,
    "defaultModel": "glm-5.3-flash",
    "id": "go",
    "keyOptional": false,
    "keyUrl": "https://opencode.ai/auth",
    "label": "OpenCode Go",
    "supportsLinkSummary": false,
    "testUsesQuota": true
  },
  {
    "defaultBaseUrl": "http://localhost:11434/v1",
    "defaultModel": "llama3.1",
    "id": "custom",
    "keyOptional": true,
    "keyUrl": null,
    "label": "Custom (OpenAI-compatible)",
    "supportsLinkSummary": false,
    "testUsesQuota": true
  }
] as const satisfies ReadonlyShape<AiProviderInfo[]>;
export const NATIVE_MODELS = {
  "custom": [
    {
      "billing": "local",
      "cost": "Local · free",
      "description": "Ollama default example — `ollama pull llama3.1` first.",
      "id": "llama3.1",
      "label": "Llama 3.1"
    },
    {
      "billing": "local",
      "cost": "Local · free",
      "description": "Good local coding model — `ollama pull qwen2.5-coder:7b`.",
      "id": "qwen2.5-coder:7b",
      "label": "Qwen 2.5 Coder 7B"
    },
    {
      "billing": "local",
      "cost": "Local · free",
      "description": "Small local model, e.g. via LM Studio.",
      "id": "gemma-3n-e4b",
      "label": "Gemma 3n E4B"
    }
  ],
  "gemini": [
    {
      "billing": "pay_per_token",
      "description": "Default. Fastest frontier text model, tuned for low-latency edits.",
      "id": "gemini-3.8-flash",
      "label": "Gemini 3.8 Flash"
    },
    {
      "billing": "pay_per_token",
      "description": "Previous-generation Flash balancing speed and multimodal ability.",
      "id": "gemini-3.6-flash",
      "label": "Gemini 3.6 Flash"
    },
    {
      "billing": "pay_per_token",
      "description": "Stable frontier model for agentic and coding-adjacent rewrites.",
      "id": "gemini-3.5-flash",
      "label": "Gemini 3.5 Flash"
    },
    {
      "billing": "pay_per_token",
      "description": "Cost-efficient stable model for high-volume simple tasks.",
      "id": "gemini-3.5-flash-lite",
      "label": "Gemini 3.5 Flash-Lite"
    },
    {
      "billing": "pay_per_token",
      "description": "Preview of the Gemini 3 Flash line. May change without notice.",
      "id": "gemini-3-flash-preview",
      "label": "Gemini 3 Flash Preview"
    },
    {
      "billing": "pay_per_token",
      "description": "Strongest reasoning in the list. Slower, best for hard rewrites.",
      "id": "gemini-3.1-pro-preview",
      "label": "Gemini 3.1 Pro Preview"
    },
    {
      "billing": "pay_per_token",
      "description": "Cost-efficient text model for high-volume simple tasks.",
      "id": "gemini-3.1-flash-lite",
      "label": "Gemini 3.1 Flash-Lite"
    }
  ],
  "go": [
    {
      "billing": "go_subscription",
      "cost": "$0.15 in / $0.50 out per 1M · $60/mo incl.",
      "description": "Recommended. Fast, high-throughput model for short writing tasks.",
      "id": "glm-5.3-flash",
      "inputPer1M": 0.15,
      "label": "GLM 5.3 Flash",
      "monthlyLimitUsd": 60.0,
      "outputPer1M": 0.5
    },
    {
      "billing": "go_subscription",
      "cost": "$0.15 in / $0.47 out per 1M · $30/mo incl.",
      "description": "Fast alternative with a low monthly usage cost.",
      "id": "qwen3.8-flash",
      "inputPer1M": 0.15,
      "label": "Qwen 3.8 Flash",
      "monthlyLimitUsd": 30.0,
      "outputPer1M": 0.47
    },
    {
      "billing": "go_subscription",
      "cost": "$0.15 in / $0.60 out per 1M · $60/mo incl.",
      "description": "Fast budget alternative for everyday edits.",
      "id": "deepseek-v4.1-flash",
      "inputPer1M": 0.15,
      "label": "DeepSeek V4.1 Flash",
      "monthlyLimitUsd": 60.0,
      "outputPer1M": 0.6
    },
    {
      "billing": "go_subscription",
      "cost": "$0.95 in / $4.00 out per 1M · $60/mo incl.",
      "description": "Strong coding model; prose edits may take longer.",
      "id": "kimi-k2.7-code",
      "inputPer1M": 0.95,
      "label": "Kimi K2.7 Code",
      "monthlyLimitUsd": 60.0,
      "outputPer1M": 4.0
    },
    {
      "billing": "go_subscription",
      "cost": "$0.15 in / $0.60 out per 1M · $30/mo incl.",
      "description": "Fast budget reasoning for everyday edits.",
      "id": "deepseek-v4-flash",
      "inputPer1M": 0.15,
      "label": "DeepSeek V4 Flash",
      "monthlyLimitUsd": 30.0,
      "outputPer1M": 0.6
    },
    {
      "billing": "go_subscription",
      "cost": "$0.40 in / $1.60 out per 1M · $60/mo incl.",
      "description": "Balanced quality for longer rewrites.",
      "id": "qwen3.7-plus",
      "inputPer1M": 0.4,
      "label": "Qwen 3.7 Plus",
      "monthlyLimitUsd": 60.0,
      "outputPer1M": 1.6
    },
    {
      "billing": "go_subscription",
      "cost": "$0.30 in / $1.20 out per 1M · $60/mo incl.",
      "description": "Capable all-rounder for writing tasks.",
      "id": "minimax-m3",
      "inputPer1M": 0.3,
      "label": "MiniMax M3",
      "monthlyLimitUsd": 60.0,
      "outputPer1M": 1.2
    },
    {
      "billing": "go_subscription",
      "cost": "$0.14 in / $0.28 out per 1M · $60/mo incl.",
      "description": "Very high request allowance per dollar.",
      "id": "mimo-v2.5",
      "inputPer1M": 0.14,
      "label": "MiMo V2.5",
      "monthlyLimitUsd": 60.0,
      "outputPer1M": 0.28
    },
    {
      "billing": "go_subscription",
      "cost": "$0.10 in / $0.20 out per 1M · $60/mo incl.",
      "description": "Meta contributor tier; trains on prompts.",
      "id": "muse-spark-1.3-contributor",
      "inputPer1M": 0.1,
      "label": "Muse Spark 1.3",
      "monthlyLimitUsd": 60.0,
      "outputPer1M": 0.2
    },
    {
      "billing": "go_subscription",
      "cost": "$0.20 in / $1.20 out per 1M · $15/mo incl.",
      "description": "Efficient OpenAI model on Go.",
      "id": "gpt-5.6-luna",
      "inputPer1M": 0.2,
      "label": "GPT 5.6 Luna",
      "monthlyLimitUsd": 15.0,
      "outputPer1M": 1.2
    },
    {
      "billing": "go_subscription",
      "cost": "$2.00 in / $6.00 out per 1M · $15/mo incl.",
      "description": "xAI flagship, smaller allowance.",
      "id": "grok-4.6",
      "inputPer1M": 2.0,
      "label": "Grok 4.6",
      "monthlyLimitUsd": 15.0,
      "outputPer1M": 6.0
    },
    {
      "billing": "free",
      "cost": "Free",
      "description": "Free stealth model, limited time.",
      "id": "union-alpha",
      "label": "Union Alpha"
    }
  ],
  "zen": [
    {
      "billing": "zen_credits",
      "cost": "$1.50 in / $7.50 out per 1M",
      "description": "Default. Same fast model as the Gemini provider.",
      "id": "gemini-3.8-flash",
      "inputPer1M": 1.5,
      "label": "Gemini 3.8 Flash",
      "outputPer1M": 7.5
    },
    {
      "billing": "zen_credits",
      "cost": "$0.15 in / $0.50 out per 1M",
      "description": "Cheapest pay-as-you-go coding model.",
      "id": "glm-5.3-flash",
      "inputPer1M": 0.15,
      "label": "GLM 5.3 Flash",
      "outputPer1M": 0.5
    },
    {
      "billing": "zen_credits",
      "cost": "$0.95 in / $4.00 out per 1M",
      "description": "Strong open coding model, good default for Zen.",
      "id": "kimi-k2.7-code",
      "inputPer1M": 0.95,
      "label": "Kimi K2.7 Code",
      "outputPer1M": 4.0
    },
    {
      "billing": "zen_credits",
      "cost": "$0.14 in / $0.28 out per 1M",
      "description": "Fast budget reasoning for everyday edits.",
      "id": "deepseek-v4-flash",
      "inputPer1M": 0.14,
      "label": "DeepSeek V4 Flash",
      "outputPer1M": 0.28
    },
    {
      "billing": "zen_credits",
      "cost": "$0.40 in / $1.60 out per 1M",
      "description": "Balanced quality for longer rewrites.",
      "id": "qwen3.7-plus",
      "inputPer1M": 0.4,
      "label": "Qwen 3.7 Plus",
      "outputPer1M": 1.6
    },
    {
      "billing": "zen_credits",
      "cost": "$0.30 in / $1.20 out per 1M",
      "description": "Capable all-rounder for writing tasks.",
      "id": "minimax-m3",
      "inputPer1M": 0.3,
      "label": "MiniMax M3",
      "outputPer1M": 1.2
    },
    {
      "billing": "zen_credits",
      "cost": "$0.20 in / $1.25 out per 1M",
      "description": "Tiny OpenAI model for quick cleanup.",
      "id": "gpt-5.4-nano",
      "inputPer1M": 0.2,
      "label": "GPT 5.4 Nano",
      "outputPer1M": 1.25
    },
    {
      "billing": "zen_credits",
      "cost": "$0.20 in / $1.20 out per 1M",
      "description": "Efficient OpenAI model with low rates.",
      "id": "gpt-5.6-luna",
      "inputPer1M": 0.2,
      "label": "GPT 5.6 Luna",
      "outputPer1M": 1.2
    },
    {
      "billing": "zen_credits",
      "cost": "$1.00 in / $5.00 out per 1M",
      "description": "Fast Anthropic model for short tasks.",
      "id": "claude-haiku-4-5",
      "inputPer1M": 1.0,
      "label": "Claude Haiku 4.5",
      "outputPer1M": 5.0
    },
    {
      "billing": "free",
      "cost": "Free",
      "description": "Free stealth model, limited time.",
      "id": "big-pickle",
      "label": "Big Pickle"
    }
  ]
} as const satisfies ReadonlyShape<Record<'gemini' | 'zen' | 'go' | 'custom', AiModelInfo[]>>;
export const NATIVE_SETTINGS = {
  "linux": {
    "aiCustomBaseUrl": null,
    "aiModels": [
      "gemini-3.8-flash"
    ],
    "aiProvider": "gemini",
    "aiReasoningMode": "fast",
    "dictationCleanupModel": null,
    "dictationHoldEnabled": true,
    "dictationHoldThresholdMs": 350,
    "dictationLanguage": "auto",
    "dictationShortcut": "Control+Alt+Space",
    "dictationTapEnabled": true,
    "dictationVocabulary": [],
    "enabledWritingActions": [
      "proofread",
      "rewrite",
      "friendly",
      "professional",
      "concise",
      "summarize",
      "key-points",
      "custom"
    ],
    "improveDictationWithAi": true,
    "launchAtLogin": false,
    "localSpeechModel": null,
    "microphoneId": null,
    "onboardingComplete": false,
    "showIdleFlowBar": false,
    "soundFeedback": true,
    "speechEngine": "system",
    "startInBackground": true,
    "theme": "system",
    "writingPresets": [],
    "writingShortcut": "Ctrl+Space"
  },
  "windows": {
    "aiCustomBaseUrl": null,
    "aiModels": [
      "gemini-3.8-flash"
    ],
    "aiProvider": "gemini",
    "aiReasoningMode": "fast",
    "dictationCleanupModel": null,
    "dictationHoldEnabled": true,
    "dictationHoldThresholdMs": 350,
    "dictationLanguage": "auto",
    "dictationShortcut": "Ctrl+Meta",
    "dictationTapEnabled": true,
    "dictationVocabulary": [],
    "enabledWritingActions": [
      "proofread",
      "rewrite",
      "friendly",
      "professional",
      "concise",
      "summarize",
      "key-points",
      "custom"
    ],
    "improveDictationWithAi": true,
    "launchAtLogin": false,
    "localSpeechModel": null,
    "microphoneId": null,
    "onboardingComplete": false,
    "showIdleFlowBar": false,
    "soundFeedback": true,
    "speechEngine": "system",
    "startInBackground": true,
    "theme": "system",
    "writingPresets": [],
    "writingShortcut": "Ctrl+Space"
  }
} as const satisfies ReadonlyShape<Record<'windows' | 'linux', AppSettings>>;
