/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/kivo.ts
 * Command: astryx theme build src/theme/kivo.ts --out src/theme/built/kivo.css
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

/// <reference path="./kivo.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const kivoTheme: DefinedTheme;
